version: '3'
services:

  frontend:
    build: 
      context: "./Front"
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
    volumes:
      - "./Front/src:/src"

  mssql:
    build: 
      context: "./DB"
    tty: true

  backend:
    build: 
      context: "./Back"
    ports:
      - "5002:5002"

  
  